name: Run tests

on: [push, pull_request]

jobs:
  test:
    name: Running tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: install rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: install dependecies
      run: pip install -r requirements.txt
    - name: build maturin develop
      uses: messense/maturin-action@v1
      with:
        maturin-version: latest
        command: develop

    - run: pip install -e .
    - run: make test
